version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./database/.env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/data/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
  express:
    build:
      context: ./webserver
    container_name: express
    ports:
      - "3000:3000"
    env_file:
      - ./webserver/.env
    depends_on:
      - postgres

  websocket:
    build:
      context: ./websocket
    container_name: websocket
    ports:
      - "8080:8080"
    env_file:
      - ./websocket/.env
    depends_on:
      - postgres
  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "5173:5173"

volumes:
  postgres_data: